### ISSUE TITLE
Add a makefile to simplify compile, test, build and push images

### ISSUE THREAD

**Issue by kagaya85** [FudanSELab/train-ticket#147]
### What would you like to be added

Add a Makefile and tool scripts

### Why is this needed

Some of the work we do now can be done through automated scripts, such as packaging, updating images, etc.
We can completely simplify these operations with some scripts and reduce the appearance of these issues like #113 

### Additional context

Tool scripts need to be put in `hack/`

#### TODO command in Makefile
- [x] package (package to jar)
- [ ] test
- [x] build (build container images)
- [x] push (push images)
